image: node:14

stages:
  - build
  - test
  - deploy

# https://docs.gitlab.com/ee/ci/caching/#caching-nodejs-dependencies
cache:
  key: '$CI_COMMIT_REF_SLUG'
  paths:
    - .npm/
  policy: pull

# https://docs.gitlab.com/ee/ci/caching/#caching-nodejs-dependencies
before_script:
  - npm ci --cache .npm --prefer-offline

build:
  stage: build
  script: npm run build -- --configuration production
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .npm/
    policy: push
  artifacts:
    name: '$CI_COMMIT_REF_SLUG-$CI_JOB_NAME'
    paths:
      - 'dist/'
    expire_in: 1 week

eslint:
  stage: test
  script: npm -s run lint -- --format=stylish > report
  artifacts:
    name: '$CI_COMMIT_REF_SLUG-$CI_JOB_NAME'
    when: on_failure
    paths:
      - 'report'
    expire_in: 1 week
  dependencies: []

prettier:
  stage: test
  script: npm -s run style > report
  artifacts:
    name: '$CI_COMMIT_REF_SLUG-$CI_JOB_NAME'
    when: on_failure
    paths:
      - 'report'
    expire_in: 1 week
  dependencies: []

unittest:
  stage: test
  script: npm -s run test -- --coverage --reporters="default" --reporters="jest-junit"
  artifacts:
    name: '$CI_COMMIT_REF_SLUG-$CI_JOB_NAME'
    when: always
    paths:
      - 'coverage/'
      - 'junit.xml'
    reports:
      cobertura: 'coverage/cobertura-coverage.xml'
      junit: 'junit.xml'
    expire_in: 1 week
  dependencies: []

#e2etest:
#  image: cypress/browsers:node14.17.0-chrome88-ff89
#  stage: test
#  script: npm -s run e2e -- --headless
#  artifacts:
#    name: '$CI_COMMIT_REF_SLUG-$CI_JOB_NAME'
#    when: on_failure
#    paths:
#      - 'reports/e2e-report.xml'
#      - 'cypress/videos/**/*.mp4'
#      - 'cypress/screenshots/**/*.png'
#    reports:
#      junit: 'reports/e2e-report.xml'
#    expire_in: 1 day
#  dependencies: []

pages:
  stage: deploy
  before_script: []
  script: mv dist/bmdl-modeler/ public/
  cache: {}
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - master
  when: manual

# See: https://git.cs.uni-paderborn.de/help/ci/docker/using_kaniko.md
buildcontainer:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  stage: deploy
  before_script: []
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  cache: {}
  dependencies: []
  only:
    - master
  needs: []
  when: manual
